### ISSUE TITLE
Failure in initSlalom()

### ISSUE THREAD

**Issue by DavidvanBruggen** [PMBio/f-scLVM#7]
I get an error in R upon trying to initialize the model, and I was wondering if this is a common problem?

the error:
> model <- initSlalom(model)
Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
traceback:
7. array(STATS, dims[perm])
6. aperm(array(STATS, dims[perm]), order(perm))
5. sweep(out$u[, 1:k], MARGIN = 2, STATS = out$d[1:k], FUN = "*", check.margin = TRUE)
4. rpca.default(Ystd[, Ion[, k]], k = 1, retx = TRUE)
3. rsvd::rpca(Ystd[, Ion[, k]], k = 1, retx = TRUE)
2. .initializePCARand(object, seed = seed, save_init = save_init)
1. initSlalom(model, seed = 222)

Does this mean I need to inclose PCA coordinates of cells, or something like this to help initialize the model?

The full code below:
> exprs_matrix <- log(networkExpressionFile[featureselection,]+1)
> OLs <- SingleCellExperiment::SingleCellExperiment(assays = list(logcounts = exprs_matrix))
> View(exprs_matrix)
> OLs
class: SingleCellExperiment 
dim: 11756 1765 
metadata(0):
assays(1): logcounts
rownames(11756): Adora1 Sntg1 ... Csf2ra eGFP
rowData names(0):
colnames(1765): counts_290.tab.A2 counts_290.tab.A3 ... counts_295.tab.P21 counts_295.tab.P22
colData names(0):
reducedDimNames(0):
spikeNames(0):
> genesets <- GSEABase::getGmt("~/Documents/SingleCellData/Networkclustering/SS2/Mouse_Human_Reactome_March_01_2018_symbol.gmt")
> model <- newSlalomModel(OLs, genesets, n_hidden = 5, min_genes = 10)
1026 annotated factors retained;  961 annotated factors dropped.
5774  genes retained for analysis.
> model <- initSlalom(model)
Error in array(STATS, dims[perm]) : 'dims' cannot be of length 0
>

**Comment by leonfodoulian** [comment]
Hi @DavidvanBruggen,

I had issued an issue in the R GitHub repository of `slalom` for this same problem 26 days ago (see [issue #10](https://github.com/PMBio/Rslalom/issues/10) for more details), but still did not receive any response from the maintainers of the package. You can find the details of why is this happening, but basically the error is due to the `sweep` function implemented in the `rsvd::rpca` function. In fact, if you have more than 499 cells in your dataset, `slalom` uses `rsvd::rpca` instead of `stats::prcomp`. I basically downloaded the function, and changed the code so that this error will not occur, by replacing `rsvd::rpca` with `stats::prcomp`. 

Best,
Leon

**Comment by DavidvanBruggen** [comment]
@leonfodoulian  Thank you! Running the adjusted code now.

**Comment by wmacnair** [comment]
Hey @DavidvanBruggen, @leonfodoulian, 

Turns out this is a tiny bug in `rsvd::rpca` (which I've reported [here](https://github.com/erichson/rSVD/issues/3)). Until that's fixed in `rsvd`, I'm fixing it via tweaked copies of `initSlalom`, `.initializePCARand` and `rpca`.

(I'm not connected with either `slalom` or `rpca`, just another user :) )

Will

**Comment by leonfodoulian** [comment]
Hi @DavidvanBruggen and @wmacnair,

This bug is now fixed in the `R slalom` package. Please refer to [issue #10](https://github.com/PMBio/Rslalom/issues/10) and [this commit](https://github.com/PMBio/Rslalom/commit/21f69dd13b09fec75dda3dbafffccd5e64034006) in the [`R` GitHub repository of `slalom`](https://github.com/PMBio/Rslalom). 

Best,
Leon

**Comment by wmacnair** [comment]
Cool, thanks @leonfodoulian!
Will

**Comment by davismcc** [comment]
Thanks, all, for the bug report. As @leonfodoulian writes, I recently fixed this issue in the repository I track for the R pkg (https://github.com/PMBio/Rslalom). This bug will be shortly fixed in the Bioconductor development version and in the next release, which is due in a few weeks.

**Comment by erichson** [comment]
I was not aware of this error in ``rsvd::rpca``, but @wmacnair was so nice to point it out to me! I will fix it later today and push a new version to CRAN. I think this should resolve the problem then.

Best,
Ben

**Comment by erichson** [comment]
The issue should be fixed now.  It will take a little while until version 0.9.1 will be available via CRAN. But, you can obtain the latest version of the ```rsvd``` package (https://github.com/erichson/rSVD) via
```
devtools::install_github("erichson/rsvd")
```

I hope that helps! I am happy for any feedback.

Best,
Ben
